---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Florian.
--- DateTime: 22/04/2022 14:58
---

---
--- Script : Anas_Ammunation
--- Author : Anas36Dev
--- DateTime: 08/10/2023 21:47
---

Citizen.CreateThread(function()
	while ESX == nil do
		TriggerEvent('esx:getSharedObject', function(obj) ESX = obj end)
		Citizen.Wait(5000)
	end
end)

local Ammunation = RageUI.CreateMenu("Ammunation", "~r~Ammunation", nil, nil, nil, nil)
local ArmesB = RageUI.CreateSubMenu(Ammunation, "Ammunation", "Catalogue")
local ArmesL = RageUI.CreateSubMenu(Ammunation, "Ammunation", "Catalogue")

function RageUI.PoolMenus:Ammunation()
    Ammunation:IsVisible(function(Items)
        if Config.Ammunation.NameOnMenu == true then 
            Items:AddLine()
            Items:AddSeparator("Nom : ~r~"..GetPlayerName(PlayerId()).."~w~")
            Items:AddLine()
        end

        ESX.TriggerServerCallback('_Anas:Ammunation:CheckLicense', function(cb)
            if cb then
                ppa = true 
            else 
                ppa = false   
            end
        end)

        Items:AddButton("Accéder au catalogue des ~r~armes blanches", nil, { IsDisabled = false, RightLabel = "→" }, function(onSelected)
        end, ArmesB)

        if ppa then
            Items:AddButton("Accéder au catalogue des ~r~armes létales", nil, { IsDisabled = false, RightLabel = "→" }, function(onSelected)
            end, ArmesL)
        else
            Items:AddButton("Vous n'avez pas le PPA", nil, { IsDisabled = true, RightLabel = "→" }, function(onSelected)
            end, ArmesL)
        end
    end, function()
    end)

    ArmesB:IsVisible(function(Items)
        for k, v in pairs(Config.Ammunation.ListeDesArmesBlanchesVendus) do
            Items:AddButton("[~r~Ammunation~s~] "..v.name, nil, { IsDisabled = false }, function(onSelected)
                local item = v.weaponName
                local label = v.name
                local prix = v.prix
                Items:AddInfo("~r~Informations", {"Prix : ", "Label : ", "ID : "}, {"~g~"..prix.."$", "~w~"..label, item})
                if (onSelected) then
                    startAnim('mp_common', 'givetake1_a')
                    ExecuteCommand('me achète une arme')
                    Citizen.Wait(2500)
                    TriggerServerEvent('_Anas:Ammunation:AchatArme', item, label, prix)
                end
            end)
        end
    end, function()
    end)

    ArmesL:IsVisible(function(Items)
        for k, v in pairs(Config.Ammunation.ListeDesArmesAFeuVendus) do
            Items:AddButton("[~r~Ammunation~s~] "..v.name, nil, { IsDisabled = false }, function(onSelected)
                local item = v.weaponName
                local label = v.name
                local prix = v.prix
                Items:AddInfo("~r~Informations", {"Prix : ", "Label : ", "ID : "}, {"~g~"..prix.."$", "~w~"..label, item})
                if (onSelected) then
                    startAnim('mp_common', 'givetake1_a')
                    ExecuteCommand('me achète une arme')
                    Citizen.Wait(2500)
                    TriggerServerEvent('_Anas:Ammunation:AchatArme', item, label, prix)
                end
            end)
        end
    end, function() 
    end)
end

Citizen.CreateThread(function()
    for k, v in pairs(Config.Ammunation.Position) do
        local blip = AddBlipForCoord(v)

        SetBlipSprite (blip, 110)
        SetBlipScale  (blip, 0.7)
        SetBlipColour (blip, 1)
        SetBlipAsShortRange(blip, true)
    
        BeginTextCommandSetBlipName('STRING')
        AddTextComponentSubstringPlayerName('Ammunation')
        EndTextCommandSetBlipName(blip)
    end
end)

function inMenuFreeze()
    while true do 
        Wait(0)
        if Ammunation.Open or ArmesB.Open or ArmesL.Open then 
            FreezeEntityPosition(PlayerPedId(), true)
        else
            FreezeEntityPosition(PlayerPedId(), false)
            break
        end
    end
end

Citizen.CreateThread(function()
    while true do
        local Timer = 500
        for k,v in pairs(Config.Ammunation.Position) do 
            local distance = GetDistanceBetweenCoords(GetEntityCoords(PlayerPedId()), v)
            if distance <= 5.0 then
                Timer = 0
                DrawMarker(21, v.x, v.y, v.z, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.3, 0.3, 0.3, 73, 143, 222, 255, 0, 1, 2, 0, nil, nil, 0)
            end
            if distance <= 1.0 then
                Timer = 0   
                ESX.ShowHelpNotification('~b~E~w~ → Parler avec le vendeur')
                if IsControlJustPressed(1,51) then
                    ExecuteCommand("me ouvre le magasin d'armes")
                    createProgressBar("Ouverture Ammunation", 216, 47, 47, 120, 2500)
                    Citizen.Wait(2500)
                    RageUI.Visible(Ammunation, true)
                    inMenuFreeze()
                end
            end
        end 
        Citizen.Wait(Timer)
    end
end)

local npc2 = {
	{hash="a_m_y_beachvesp_01", x = 21.47, y = -1105.03, z = 29.70, a=151.27}, 
}

Citizen.CreateThread(function()
    if Config.Ammunation.NPC == true then 
        for _, item2 in pairs(npc2) do
            local hash = GetHashKey(item2.hash)
            while not HasModelLoaded(hash) do
            RequestModel(hash)
            Wait(20)
            end
            ped2 = CreatePed("PED_TYPE_CIVFEMALE", item2.hash, item2.x, item2.y, item2.z-0.92, item2.a, false, true)
            SetBlockingOfNonTemporaryEvents(ped2, true)
            FreezeEntityPosition(ped2, true)
            SetEntityInvincible(ped2, true)
        end
    end
end)

function startAnim(lib, anim)
    ESX.Streaming.RequestAnimDict(lib, function()
        TaskPlayAnim(PlayerPedId(), lib, anim, 8.0, -8.0, -1, 0, 0.0, false, false, false)
    end)
end

function createProgressBar(Text,r,g,b,a,Timing,NoTiming)
	local petitpoint = {".","..","...",""}
    if not Timing then 
        return 
    end
    killProgressBar()
    haveprogress = true
    Citizen.CreateThread(function()
        local Timing1, Timing2 = .0, GetGameTimer() + Timing
        local E, Timing3 = ""
        while haveprogress and (not NoTiming and Timing1 < 1) do
            Citizen.Wait(0)
            if not NoTiming or Timing1 < 1 then 
                Timing1 = 1-((Timing2 - GetGameTimer())/Timing)
            end
            if not Timing3 or GetGameTimer() >= Timing3 then
                Timing3 = GetGameTimer()+500;
                E = petitpoint[string.len(E)+1] or ""
            end;
            DrawRect(.5,.875,.15,.03,0,0,0,100)
            local y, endroit=.15-.0025,.03-.005;
            local chance = math.max(0,math.min(y,y*Timing1))
            DrawRect((.5-y/2)+chance/2,.875,chance,endroit,r,g,b,a) -- 0,155,255,125
            DrawNiceText(.5,.875-.0125,.3,(Text or"Action en cours")..E,0,0,false)
        end;
        killProgressBar()
    end)
end

function killProgressBar()
    haveprogress = nil 
end

function DrawNiceText(Text,Text3,Taille,Text2,Font,Justi,havetext)
    SetTextFont(Font)
    SetTextScale(Taille,Taille)
    SetTextColour(255,255,255,255)
    SetTextJustification(Justi or 1)
    SetTextEntry("STRING")
        if havetext then 
            SetTextWrap(Text,Text+.1)
        end;
        AddTextComponentString(Text2)
    DrawText(Text,Text3)
end